### PR TITLE
Calendar Addition and Discord Logo Change

### PR DESCRIPTION
**Pull request by dhkatz**
After discussing with @JejuneKai on Discord we've decided it would be in
everyone's best interests to add a calendar button to the hotbar on the
subreddit.

[Image of what I am talking about](https://u.nya.is/kfhwdd.png)

We recently began planning events for the subreddit and found it
challenging to coordinate times with other tournaments (like PCL,
Pheonix, and Sylphin's). If we were able to have an icon that links to
a page on the wiki, we could consolidate a list of known events and
times. This way we could let others know when the subreddit's own events
would be and to plan around them (or possible allow tournaments to
submit their own dates to be added, I would handle if so desired).

Find me on Github or /u/MCiLuziionz or Doctor Jew#6931 (Discord)

### CODE REVIEW

**Comment by Morasel** [comment]
This would be a fantastic addition to the sub. There are plenty of online calendars that would do the job. I have used www.teamup.com before and it was pretty good. You can send links with specific levels of access (read only, additions only etc). I'm sure there are other good options too.

**Review by jamieshepherd — APPROVED** [review]
Looks good to me, @JejuneKai can you pull changes, build + push to live? (Ensure you upload two new images).

**Comment by dhkatz** [comment]
Many thanks, especially with Epic's new competitive changes.

**Comment by Morasel** [comment]
Great addition guys! Will event organisers have add access to the calendar or will we contact @JejuneKai to add details?

**Comment by jamieshepherd** [comment]
I think it makes the most sense to have Jejune or admins run the calendar with organisers requesting they be added.

**Comment by absorbent41** [comment]
To keep the format tidy we're going to be making additions manually for now. I'm sure in the future we can distribute specific organizer links to Epic sanctioned event admins and other well known event organizers.

**Comment by Morasel** [comment]
Yeah I saw the Reddit thread after commenting here. I think that's a good idea. Thanks for doing this guys! Awesome work!

**Pull request merged**
