### PR TITLE
Flairs Update

### PR DESCRIPTION
**Pull request by absorbent41**
So I know you've already shot me down twice for this, but I've been talking with @DoctorJew and both JShredz and realtrendy are on board (even Janelle, although she doesn't really count), so I hope you'll hear me out. We've taken the liberty of putting together flair sheets for challenger, master and the various NPCs with the appropriate code that points to each sheet with its own css class. Even if they aren't used, there's no harm in having them available in the css. They can be used for whatever, be it identifying moderators or signifying key community members. [Here's an example.](http://i.imgur.com/qTzGKxD.png)

**Encouraging positivity**

Earlier this morning Epic put up a post about tackling toxicity in the community. They've asked realtrendy to write up a post about encouraging positivity by the end of the week and he's going to bring up the Reddit ARAMs as a means of encouraging good sportsmanship in the community through casual community events. The idea was to have the winners sport master flairs of their heroes for an indefinite amount of time, with the runners up sporting challenger flairs. While it's nothing spectacular, it's something to show off and encourages more participation in the subreddit as something to achieve. As you've mentioned, it would create a back-and-forth with people swapping flairs, so I would be more than happy to handle any flair requests that come up and direct all requests to myself in order to lessen the work for everyone else.

Just take a look. Don't they look cool? Especially Orb Prime <3

### CODE REVIEW

**Comment by dhkatz** [comment]
Orb Prime is thicc, looks good. (You're welcome for css tho)

**Comment by jamieshepherd** [comment]
Flairs besides heroes isn't something I want - having flairs originally was a big enough decision to stop the subreddit from looking tacky so they had to be "right" - minions very much go against that. Master flairs (or custom flairs, since those look pretty bad) for tournaments wins weren't a bad idea, but not for ARAM - it's not a tournament, it's just a fun get together.

Sorry if you feel like you've wasted time, but this was all discussed before.

**Comment by absorbent41** [comment]
The idea wasn't to introduce minion flairs to everyone, they were meant to distinguish certain members of the community, such as dataminers, tournament organizers, moderators, wiki contributors, et cetera. We don't need to use all the flairs, it's just a repository so they're available to us. Obviously some look better than others.(edited)
While I get where you're coming from, I think you're exaggerating the importance of flairs. ARAMs are just for fun (ARAMs weren't all we had in mind), but the idea isn't for it to be a reward for high end players, it's just something to show for participating in a community event. While it's great that the subreddit looks professional, it's still a community. We'd do well to embrace that.

**Comment by dhkatz** [comment]
Users wouldn't even see the flairs in the side bar, they would still see the default ones. These are special rewards for Epic/Subreddit tournaments and other contests. I know I'm not a moderator, but I feel like you guys could really start to incentivize more participation on the subreddit and in events.

**Pull request closed without merging**
